version: '3'
services:

  php7: 
    image:  myphp
    hostname:  php7
    volumes:
      - ~/site01/www:/var/www/html
    ports:
      - "8080:80"
    links:
      - mysql
    command: [ "/run.sh" ]
  mysql:
    image: mysql:5.7
    hostname: mysql01
    environment:
      MYSQL_ROOT_PASSWORD: mypass01
    volumes:
      - ~/site01/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    links:
      - mysql:db
    ports:
      - "8081:80"
    
